/*
 * GoCardless Bank Account Data API
 *
 * Securely access your user's bank account information for better lending, accounting, verification and financial management.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdditionalAccountDataSchema : AdditionalAccountDataSchema.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdditionalAccountDataSchema {
    /// secondaryIdentification
    #[serde(
        rename = "secondaryIdentification",
        skip_serializing_if = "Option::is_none"
    )]
    pub secondary_identification: Option<String>,
}

impl AdditionalAccountDataSchema {
    /// AdditionalAccountDataSchema.
    pub fn new() -> AdditionalAccountDataSchema {
        AdditionalAccountDataSchema {
            secondary_identification: None,
        }
    }
}
