/*
 * GoCardless Bank Account Data API
 *
 * Securely access your user's bank account information for better lending, accounting, verification and financial management.
 *
 * The version of the OpenAPI document: 2.0.7
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BalanceAfterTransactionSchema : BalanceAfterTransactionSchema.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceAfterTransactionSchema {
    /// balanceAmount
    #[serde(rename = "balanceAmount")]
    pub balance_amount: Box<models::TransactionAmountSchema>,
    /// balanceType
    #[serde(rename = "balanceType")]
    pub balance_type: String,
}

impl BalanceAfterTransactionSchema {
    /// BalanceAfterTransactionSchema.
    pub fn new(
        balance_amount: models::TransactionAmountSchema,
        balance_type: String,
    ) -> BalanceAfterTransactionSchema {
        BalanceAfterTransactionSchema {
            balance_amount: Box::new(balance_amount),
            balance_type,
        }
    }
}
