/*
 * GoCardless Bank Account Data API
 *
 * Securely access your user's bank account information for better lending, accounting, verification and financial management.
 *
 * The version of the OpenAPI document: 2.0.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReconfirmationRetrieveRequest : EUA reconfirmation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReconfirmationRetrieveRequest {
    /// Optional redirect URL for reconfirmation to override requisition's redirect.
    #[serde(
        rename = "redirect",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub redirect: Option<Option<String>>,
}

impl ReconfirmationRetrieveRequest {
    /// EUA reconfirmation.
    pub fn new() -> ReconfirmationRetrieveRequest {
        ReconfirmationRetrieveRequest { redirect: None }
    }
}
