/*
 * GoCardless Bank Account Data API
 *
 * Securely access your user's bank account information for better lending, accounting, verification and financial management.
 *
 * The version of the OpenAPI document: 2.0.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuccessfulDeleteResponse {
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "detail")]
    pub detail: String,
}

impl SuccessfulDeleteResponse {
    pub fn new(summary: String, detail: String) -> SuccessfulDeleteResponse {
        SuccessfulDeleteResponse { summary, detail }
    }
}
