name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        env:
            RUSTFLAGS: '-Dwarnings'

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Rust toolchain
              run: rustup toolchain install stable --no-self-update --profile default --target wasm32-unknown-unknown

            - name: Set up Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
                  save-if: ${{ github.ref == 'refs/heads/main' }}

            - name: Check formatting
              run: cargo fmt --all --check

            - name: Lint
              run: cargo clippy --all-features

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Rust toolchain
              run: rustup toolchain install stable --no-self-update --profile default --target wasm32-unknown-unknown

            - name: Set up Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
                  save-if: ${{ github.ref == 'refs/heads/main' }}

            - name: Test
              run: cargo test --all-features
