name: Publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        name: Publish
        uses: NixySoftware/.github/.github/workflows/publish.yml@6b03162f358358a3a6e814434ada3a73997714a9 # v0.6.0
        with:
            enable-rust: true
            enable-typescript: false
